// swift-tools-version: 6.4
import PackageDescription

let package = Package(
    name: "swift-coder",
    platforms: [.macOS(.v27), .iOS(.v27), .tvOS(.v27), .watchOS(.v27), .visionOS(.v27)],
    products: [
        .library(name: "Coder", targets: ["Coder"]),
        .library(name: "Coder Foundation Integration", targets: ["Coder Foundation Integration"]),
        .library(name: "Coder Test Support", targets: ["Coder Test Support"]),
        .executable(name: "CoderUserRecords", targets: ["User Records Example"]),
    ],
    traits: [
        .trait(name: "Choice", description: "Classified parser choice coding", enabledTraits: ["Checkpoint"]),
        .trait(name: "Always", description: "The infallible Void unit grammar"),
        .trait(name: "Either", description: "Conditional coder construction"),
        .trait(name: "Pair", description: "Safe structural product composition", enabledTraits: ["Either"]),
        .trait(name: "Skip", description: "Canonical Void grammar composition", enabledTraits: ["Either"]),
        .trait(name: "Map", description: "Bidirectional conversion and failure mapping"),
        .trait(name: "Optic", description: "Optic conversion and explicit case branches", enabledTraits: ["Map"]),
        .trait(name: "Repetition", description: "Bounded, rejection-aware element and separator composition", enabledTraits: ["Checkpoint"]),
        .trait(name: "Predicate", description: "Borrowed value validation in both directions"),
        .trait(name: "Checkpoint", description: "Rejection-aware alternatives and repetition"),
        .trait(name: "Byte", description: "Absorbed Byte integration"),
        .trait(name: "Carrier", description: "Absorbed Carrier integration", enabledTraits: ["Map"]),
        .trait(name: "Operation", description: "Absorbed Operation integration", enabledTraits: ["Optic"]),
        .trait(name: "IteratorLeaves", description: "Approved IteratorLeaves integration", enabledTraits: ["Either"]),
    ],
    dependencies: [
        .package(url: "https://github.com/swift-atoms/swift-always.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-repetition.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-cardinal.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-predicate.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-parser.git", branch: "main", traits: [
            .trait(name: "Choice", condition: .when(traits: ["Choice"])),
            .trait(name: "IteratorLeaves", condition: .when(traits: ["IteratorLeaves"])),
            .trait(name: "Always", condition: .when(traits: ["Always"])),
            .trait(name: "Predicate", condition: .when(traits: ["Predicate"])),
            .trait(name: "Repetition", condition: .when(traits: ["Repetition"])),
            .trait(name: "Either", condition: .when(traits: ["Either", "IteratorLeaves", "Pair", "Skip"])),
            .trait(name: "Pair", condition: .when(traits: ["Pair"])),
            .trait(name: "Skip", condition: .when(traits: ["Skip"])),
            .trait(name: "Map", condition: .when(traits: ["Map", "Carrier", "Operation", "Optic"])),
            .trait(name: "Optic", condition: .when(traits: ["Optic", "Operation"])),
            .trait(name: "Iterator", condition: .when(traits: ["IteratorLeaves"])),
        ]),
        .package(url: "https://github.com/swift-atoms/swift-serializer.git", branch: "main", traits: [
            .trait(name: "Byte", condition: .when(traits: ["Byte"])),
            .trait(name: "Always", condition: .when(traits: ["Always"])),
            .trait(name: "Repetition", condition: .when(traits: ["Repetition"])),

            .trait(name: "Either", condition: .when(traits: ["Either", "IteratorLeaves", "Pair", "Skip"])),
            .trait(name: "Pair", condition: .when(traits: ["Pair"])),
            .trait(name: "Map", condition: .when(traits: ["Map", "Carrier", "Operation", "Optic"])),
            .trait(name: "Optic", condition: .when(traits: ["Optic", "Operation"])),
        ]),
        .package(url: "https://github.com/swift-atoms/swift-either.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-pair.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-skip.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-map.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-optic.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-checkpoint.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-byte.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-carrier.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-operation.git", branch: "main"),
        .package(url: "https://github.com/swift-atoms/swift-iterator.git", branch: "main"),
    ],
    targets: [
        .target(name: "Coder", dependencies: [
            .product(name: "Always", package: "swift-always", condition: .when(traits: ["Always"])),
            .product(name: "Repetition", package: "swift-repetition", condition: .when(traits: ["Repetition"])),
            .product(name: "Cardinal", package: "swift-cardinal", condition: .when(traits: ["Repetition"])),
            .product(name: "Predicate", package: "swift-predicate", condition: .when(traits: ["Predicate"])),
            .product(name: "Parser", package: "swift-parser"),
            .product(name: "Serializer", package: "swift-serializer"),
            .product(name: "Either", package: "swift-either", condition: .when(traits: ["Either", "IteratorLeaves", "Pair", "Skip"])),
            .product(name: "Pair", package: "swift-pair", condition: .when(traits: ["Pair"])),
            .product(name: "Skip", package: "swift-skip", condition: .when(traits: ["Skip"])),
            .product(name: "Map", package: "swift-map", condition: .when(traits: ["Map", "Carrier", "Operation", "Optic"])),
            .product(name: "Optic", package: "swift-optic", condition: .when(traits: ["Optic", "Operation"])),
            .product(name: "Checkpoint", package: "swift-checkpoint", condition: .when(traits: ["Checkpoint", "Choice", "Repetition"])),
                .product(name: "Byte", package: "swift-byte", condition: .when(traits: ["Byte"])),
                .product(name: "Carrier", package: "swift-carrier", condition: .when(traits: ["Carrier"])),
                .product(name: "Operation", package: "swift-operation", condition: .when(traits: ["Operation"])),
                .product(name: "Iterator", package: "swift-iterator", condition: .when(traits: ["IteratorLeaves"])),
            ]),
        .target(name: "Coder Foundation Integration", dependencies: ["Coder"]),
        .target(name: "Coder Test Support", dependencies: ["Coder"], path: "Tests/Support"),
        .testTarget(name: "Coder Tests", dependencies: ["Coder", "Coder Test Support", "User Records Model"]),
        .target(name: "User Records Model", dependencies: ["Coder"], path: "Examples/User Records/Model"),
        .executableTarget(name: "User Records Example", dependencies: ["User Records Model"], path: "Examples/User Records/Executable"),
        .testTarget(name: "Absorbed swift-byte-coder Byte Coder Tests", dependencies: [.product(name: "Byte", package: "swift-byte", condition: .when(traits: ["Byte"])), .target(name: "Coder"), .product(name: "Parser", package: "swift-parser", condition: .when(traits: ["Byte"])), .product(name: "Serializer", package: "swift-serializer", condition: .when(traits: ["Byte"]))], path: "Tests/Absorbed/swift-byte-coder/Byte Coder Tests"),
        .testTarget(name: "Absorbed swift-string-coder String Coder Tests", dependencies: [.product(name: "Byte", package: "swift-byte", condition: .when(traits: ["Byte"])), .target(name: "Coder")], path: "Tests/Absorbed/swift-string-coder/String Coder Tests"),
        .testTarget(name: "Absorbed swift-operation-coder Operation Coder Tests", dependencies: [.target(name: "Coder"), .product(name: "Operation", package: "swift-operation", condition: .when(traits: ["Operation"])), .product(name: "Optic", package: "swift-optic", condition: .when(traits: ["Operation"])), .product(name: "Parser", package: "swift-parser", condition: .when(traits: ["Operation"])), .product(name: "Serializer", package: "swift-serializer", condition: .when(traits: ["Operation"]))], path: "Tests/Absorbed/swift-operation-coder/Operation Coder Tests"),
        .testTarget(name: "Approved Iterator Coding Tests", dependencies: ["Coder", .product(name: "Parser", package: "swift-parser"), .product(name: "Serializer", package: "swift-serializer"), .product(name: "Iterator", package: "swift-iterator"), .product(name: "Either", package: "swift-either")], path: "Tests/Approved Iterator Coding"),
    ],
    swiftLanguageModes: [.v6]
)
for target in package.targets {
    target.swiftSettings = [
        .strictMemorySafety(),
        .enableUpcomingFeature("ExistentialAny"),
        .enableUpcomingFeature("InternalImportsByDefault"),
        .enableUpcomingFeature("MemberImportVisibility"),
        .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
        .enableUpcomingFeature("InferIsolatedConformances"),
        .enableExperimentalFeature("Lifetimes"),
        .enableExperimentalFeature("MoveOnlyTuples"),
    ]
}
